name: Metrics embed

on:
  schedule: [{cron: "0 * * * *"}]  # Atualiza a cada hora
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: lailtonjunior
          template: classic
          base: header, activity, community, repositories, metadata
