name: 🦉 GitHub Metrics Full Setup

on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Base Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: github-metrics
          base: header, activity, community, repositories, metadata

      - name: Achievements Compact
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: github-metrics
          plugin_achievements: yes
          plugin_achievements_display: compact

      - name: Activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: github-metrics
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create

      - name: Calendar Compact
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: github-metrics
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_calendar_compact: yes

      - name: Code Stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.code.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: github-metrics
          plugin_code: yes
          plugin_code_languages: javascript, typescript, python, html, css, sql

      - name: Contributors by Categories
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.contributors.categories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: github-metrics
          plugin_contributors: yes
          plugin_contributors_sections: categories
          plugin_contributors_categories: |
            {
              "Plugins / Templates": ["source/plugins/**", "source/templates/**"],
              "Documentation": ["README.md", "**/README.md", "**/metadata.yml"],
              "Code": ["source/**", "Dockerfile"]
            }

      - name: Discussions Participation
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.discussions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: github-metrics
          plugin_discussions: yes

      - name: Habits
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: github-metrics
          plugin_habits: yes

      - name: Languages Used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: github-metrics
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used

      - name: Notable Projects
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.projects.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: github-metrics
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_projects_descriptions: yes

      - name: Traffic
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.traffic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: github-metrics
          plugin_traffic: yes
