name: Métricas Avançadas do Perfil (SkaliKing)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  # Job Principal: Gera as estatísticas base, linguagens e atividade
  metrics_base:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: lailtonjunior
          filename: metrics.base.svg
          template: classic
          base: activity, community
          config_display: "dark, nocturnal"
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_lines: yes

  # Job das Conquistas: Gera a imagem de conquistas
  metrics_achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: lailtonjunior
          filename: metrics.achievements.svg
          template: classic
          base: "" # Base vazia para um card limpo
          config_display: "dark, nocturnal"
          plugin_achievements: yes
          plugin_achievements_threshold: C

  # Job do Calendário: Gera a imagem do calendário de contribuições
  metrics_calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: lailtonjunior
          filename: metrics.calendar.svg
          template: classic
          base: "" # Base vazia
          config_display: "dark, nocturnal"
          plugin_calendar: yes

  # Job das Contribuições Notáveis: Gera a imagem de discussões, etc.
  metrics_notable:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: lailtonjunior
          filename: metrics.notable.svg
          template: classic
          base: "" # Base vazia
          config_display: "dark, nocturnal"
          plugin_discussions: yes
          plugin_reactions: yes
          plugin_reactions_limit: 100
