name: 🦉 GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}]  # Atualiza todo dia à meia-noite
  workflow_dispatch:              # Permite rodar manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Base
          user: lailtonjunior
          template: classic
          base: header, activity, community, repositories, metadata

          # Plugins extras:
          config_timezone: America/Sao_Paulo

          # Estatísticas de linguagens
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 6

          # Contribuições recentes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14

          # Contribuições por horário
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # Commits por dia
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Achievements (Conquistas)
          plugin_achievements: yes
          plugin_achievements_display: compact

          # Projetos fixos (pode alterar os repositórios se quiser)
          plugin_projects: yes
          plugin_projects_repositories:
