# Nome do Workflow para identificação na aba "Actions" do GitHub
name: Métricas Completas do Perfil (SkaliKing)

# Gatilhos: Define quando este workflow deve ser executado
on:
  # Executa toda madrugada para manter as métricas atualizadas
  schedule:
    - cron: '0 3 * * *' # 03:00 UTC
  # Permite que você execute o workflow manualmente pela aba "Actions"
  workflow_dispatch:
  # Executa toda vez que você envia um commit para a branch principal
  push:
    branches:
      - main
      - master

# Define todos os "trabalhos" (jobs) a serem executados em paralelo
jobs:
  # Job para Linguagens, Linhas de Código e Contribuições
  languages_and_lines:
    name: "Linguagens, Linhas e Contribs"
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: lailtonjunior
          filename: metrics.languages.svg
          base: "" # Base vazia para um card limpo
          config_display: "dark, nocturnal"
          config_timezone: America/Sao_Paulo
          # Plugins a serem incluídos neste card
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_lines: yes
          plugin_contributors: yes
          plugin_contributors_sections: "projects" # Contribuições em projetos

  # Job para Hábitos de Codificação
  habits:
    name: "Hábitos de Codificação"
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: lailtonjunior
          filename: metrics.habits.svg
          base: ""
          config_display: "dark, nocturnal"
          config_timezone: America/Sao_Paulo
          plugin_habits: yes
          plugin_habits_charts: yes # Mostra os gráficos de hora/dia

  # Job para Projetos e Discussões
  projects_and_discussions:
    name: "Projetos e Discussões"
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: lailtonjunior
          filename: metrics.projects.svg
          base: ""
          config_display: "dark, nocturnal"
          config_timezone: America/Sao_Paulo
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_discussions: yes

  # Job para Conquistas (Achievements)
  achievements:
    name: "Conquistas"
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: lailtonjunior
          filename: metrics.achievements.svg
          base: ""
          config_display: "dark, nocturnal"
          plugin_achievements: yes
          plugin_achievements_threshold: C # Mostra do Rank S ao C

  # Job para Calendário Compacto
  calendar:
    name: "Calendário Compacto"
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: lailtonjunior
          filename: metrics.calendar.svg
          base: ""
          config_display: "dark, nocturnal"
          plugin_calendar: yes
          plugin_calendar_limit: 1 # Usa a versão compacta do calendário

  # Job para Tráfego do Repositório
  traffic:
    name: "Tráfego"
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # NOTA: O token padrão tem acesso limitado. Para tráfego, pode ser necessário
          # criar um Personal Access Token (PAT) com permissão de 'repo' e salvá-lo
          # como um secret chamado METRICS_TOKEN_WITH_REPO_ACCESS no seu repositório.
          token: ${{ secrets.METRICS_TOKEN_WITH_REPO_ACCESS || secrets.GITHUB_TOKEN }}
          user: lailtonjunior
          filename: metrics.traffic.svg
          base: ""
          config_display: "dark, nocturnal"
          plugin_traffic: yes

  # Job para Atividade Recente
  activity:
    name: "Atividade Recente"
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: lailtonjunior
          filename: metrics.activity.svg
          base: ""
          config_display: "dark, nocturnal"
          plugin_activity: yes
          plugin_activity_limit: 5 # Número de atividades a serem mostradas

  # Job para Trecho de Código Aleatório
  code:
    name: "Trecho de Código Aleatório"
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: lailtonjunior
          filename: metrics.code.svg
          base: ""
          config_display: "dark, nocturnal"
          plugin_code: yes
          plugin_code_lines: 6 # Número de linhas do trecho
